import Footer from "@/components/footer/Footer";
import Navbar from "@/components/nav/Navbar";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import CartProvider from "../../providers/CartProvider";
import "./globals.css";
import {Toaster} from "react-hot-toast"
import { getCurrentUser } from "./actions/getCurrentUser";


const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "nextjs E-commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} text-slate-700`}>
        <Toaster/>
        <CartProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
